title: Thrift Savings Plan
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# To enable search, uncomment the search section
# You will need to setup a search account with search.gov
# https://search.usa.gov/signup
# Your search_site_handle value is from the search.gov settings page.

search_site_handle: searchgov-site-handle

# Build settings
markdown: kramdown

styles:
  - /assets/css/main.css
  - /assets/css/jquery-ui-1.8.18.custom.css

scripts:
  - /assets/js/jquery-1-8-2.min.js
  - /assets/js/jquery.tools.min_125.js
  - /assets/js/jquery.numeric.js
  - /assets/js/jquery-ui-1.8.18.custom.min.js

sass:
  load_paths:
    - _sass
    - node_modules
  style: compressed

exclude:
  - circle.yml
  - README.md
  - package-lock.json
  - package.json
  - vendor
