title: Thrift Savings Plan
description:
baseurl: "/sandbox" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# To enable search, uncomment the search section
# You will need to setup a search account with search.gov
# https://search.usa.gov/signup
# Your search_site_handle value is from the search.gov settings page.

search_site_handle: searchgov-site-handle

# Build settings
markdown: kramdown

styles:
  - /assets/css/main.css

sass:
  load_paths:
    - _sass
    - node_modules
  style: compressed
