version: 2
jobs:
  build:
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
  deploy-job:
    steps:
      - run:
          name: Install dependencies
          command: bundle exec jekyll build
      - run:
          name: Overrides tests
          command: echo "Tests disabled"
      - run:
          name: Deploy master brnach to AWS
          command: aws s3 sync ./_site s3://tspdev.gov/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
